/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'
import { Route as ApiPublicTranscodeKeyRouteImport } from './routes/api/public/transcode-key'
import { Route as ApiPublicTranscodeRouteImport } from './routes/api/public/transcode'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'
import { Route as ApiPublicTelegramCheckEnvRouteImport } from './routes/api/public/telegram/check-env'
import { Route as ApiPublicSmsSendRouteImport } from './routes/api/public/sms/send'
import { Route as ApiPublicPaymentsStripeVerifyRouteImport } from './routes/api/public/payments/stripe-verify'
import { Route as ApiPublicPaymentsStripeRouteImport } from './routes/api/public/payments/stripe'
import { Route as ApiPublicPaymentsGiftRouteImport } from './routes/api/public/payments/gift'
import { Route as ApiPublicPaymentsCheckoutRouteImport } from './routes/api/public/payments/checkout'
import { Route as ApiPublicCronExpireRouteImport } from './routes/api/public/cron/expire'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscodeKeyRoute = ApiPublicTranscodeKeyRouteImport.update({
  id: '/api/public/transcode-key',
  path: '/api/public/transcode-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscodeRoute = ApiPublicTranscodeRouteImport.update({
  id: '/api/public/transcode',
  path: '/api/public/transcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramCheckEnvRoute =
  ApiPublicTelegramCheckEnvRouteImport.update({
    id: '/api/public/telegram/check-env',
    path: '/api/public/telegram/check-env',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSmsSendRoute = ApiPublicSmsSendRouteImport.update({
  id: '/api/public/sms/send',
  path: '/api/public/sms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsStripeVerifyRoute =
  ApiPublicPaymentsStripeVerifyRouteImport.update({
    id: '/api/public/payments/stripe-verify',
    path: '/api/public/payments/stripe-verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsStripeRoute = ApiPublicPaymentsStripeRouteImport.update({
  id: '/api/public/payments/stripe',
  path: '/api/public/payments/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsGiftRoute = ApiPublicPaymentsGiftRouteImport.update({
  id: '/api/public/payments/gift',
  path: '/api/public/payments/gift',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsCheckoutRoute =
  ApiPublicPaymentsCheckoutRouteImport.update({
    id: '/api/public/payments/checkout',
    path: '/api/public/payments/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronExpireRoute = ApiPublicCronExpireRouteImport.update({
  id: '/api/public/cron/expire',
  path: '/api/public/cron/expire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/movie/$id': typeof MovieIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api/public/transcode': typeof ApiPublicTranscodeRoute
  '/api/public/transcode-key': typeof ApiPublicTranscodeKeyRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/cron/expire': typeof ApiPublicCronExpireRoute
  '/api/public/payments/checkout': typeof ApiPublicPaymentsCheckoutRoute
  '/api/public/payments/gift': typeof ApiPublicPaymentsGiftRoute
  '/api/public/payments/stripe': typeof ApiPublicPaymentsStripeRoute
  '/api/public/payments/stripe-verify': typeof ApiPublicPaymentsStripeVerifyRoute
  '/api/public/sms/send': typeof ApiPublicSmsSendRoute
  '/api/public/telegram/check-env': typeof ApiPublicTelegramCheckEnvRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/movie/$id': typeof MovieIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api/public/transcode': typeof ApiPublicTranscodeRoute
  '/api/public/transcode-key': typeof ApiPublicTranscodeKeyRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/cron/expire': typeof ApiPublicCronExpireRoute
  '/api/public/payments/checkout': typeof ApiPublicPaymentsCheckoutRoute
  '/api/public/payments/gift': typeof ApiPublicPaymentsGiftRoute
  '/api/public/payments/stripe': typeof ApiPublicPaymentsStripeRoute
  '/api/public/payments/stripe-verify': typeof ApiPublicPaymentsStripeVerifyRoute
  '/api/public/sms/send': typeof ApiPublicSmsSendRoute
  '/api/public/telegram/check-env': typeof ApiPublicTelegramCheckEnvRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/movie/$id': typeof MovieIdRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api/public/transcode': typeof ApiPublicTranscodeRoute
  '/api/public/transcode-key': typeof ApiPublicTranscodeKeyRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/cron/expire': typeof ApiPublicCronExpireRoute
  '/api/public/payments/checkout': typeof ApiPublicPaymentsCheckoutRoute
  '/api/public/payments/gift': typeof ApiPublicPaymentsGiftRoute
  '/api/public/payments/stripe': typeof ApiPublicPaymentsStripeRoute
  '/api/public/payments/stripe-verify': typeof ApiPublicPaymentsStripeVerifyRoute
  '/api/public/sms/send': typeof ApiPublicSmsSendRoute
  '/api/public/telegram/check-env': typeof ApiPublicTelegramCheckEnvRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/movie/$id'
    | '/api/public/setup-admin'
    | '/api/public/transcode'
    | '/api/public/transcode-key'
    | '/api/public/upload'
    | '/api/public/cron/expire'
    | '/api/public/payments/checkout'
    | '/api/public/payments/gift'
    | '/api/public/payments/stripe'
    | '/api/public/payments/stripe-verify'
    | '/api/public/sms/send'
    | '/api/public/telegram/check-env'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/movie/$id'
    | '/api/public/setup-admin'
    | '/api/public/transcode'
    | '/api/public/transcode-key'
    | '/api/public/upload'
    | '/api/public/cron/expire'
    | '/api/public/payments/checkout'
    | '/api/public/payments/gift'
    | '/api/public/payments/stripe'
    | '/api/public/payments/stripe-verify'
    | '/api/public/sms/send'
    | '/api/public/telegram/check-env'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/movie/$id'
    | '/api/public/setup-admin'
    | '/api/public/transcode'
    | '/api/public/transcode-key'
    | '/api/public/upload'
    | '/api/public/cron/expire'
    | '/api/public/payments/checkout'
    | '/api/public/payments/gift'
    | '/api/public/payments/stripe'
    | '/api/public/payments/stripe-verify'
    | '/api/public/sms/send'
    | '/api/public/telegram/check-env'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  MovieIdRoute: typeof MovieIdRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
  ApiPublicTranscodeRoute: typeof ApiPublicTranscodeRoute
  ApiPublicTranscodeKeyRoute: typeof ApiPublicTranscodeKeyRoute
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
  ApiPublicCronExpireRoute: typeof ApiPublicCronExpireRoute
  ApiPublicPaymentsCheckoutRoute: typeof ApiPublicPaymentsCheckoutRoute
  ApiPublicPaymentsGiftRoute: typeof ApiPublicPaymentsGiftRoute
  ApiPublicPaymentsStripeRoute: typeof ApiPublicPaymentsStripeRoute
  ApiPublicPaymentsStripeVerifyRoute: typeof ApiPublicPaymentsStripeVerifyRoute
  ApiPublicSmsSendRoute: typeof ApiPublicSmsSendRoute
  ApiPublicTelegramCheckEnvRoute: typeof ApiPublicTelegramCheckEnvRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcode-key': {
      id: '/api/public/transcode-key'
      path: '/api/public/transcode-key'
      fullPath: '/api/public/transcode-key'
      preLoaderRoute: typeof ApiPublicTranscodeKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcode': {
      id: '/api/public/transcode'
      path: '/api/public/transcode'
      fullPath: '/api/public/transcode'
      preLoaderRoute: typeof ApiPublicTranscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/check-env': {
      id: '/api/public/telegram/check-env'
      path: '/api/public/telegram/check-env'
      fullPath: '/api/public/telegram/check-env'
      preLoaderRoute: typeof ApiPublicTelegramCheckEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms/send': {
      id: '/api/public/sms/send'
      path: '/api/public/sms/send'
      fullPath: '/api/public/sms/send'
      preLoaderRoute: typeof ApiPublicSmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/stripe-verify': {
      id: '/api/public/payments/stripe-verify'
      path: '/api/public/payments/stripe-verify'
      fullPath: '/api/public/payments/stripe-verify'
      preLoaderRoute: typeof ApiPublicPaymentsStripeVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/stripe': {
      id: '/api/public/payments/stripe'
      path: '/api/public/payments/stripe'
      fullPath: '/api/public/payments/stripe'
      preLoaderRoute: typeof ApiPublicPaymentsStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/gift': {
      id: '/api/public/payments/gift'
      path: '/api/public/payments/gift'
      fullPath: '/api/public/payments/gift'
      preLoaderRoute: typeof ApiPublicPaymentsGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/checkout': {
      id: '/api/public/payments/checkout'
      path: '/api/public/payments/checkout'
      fullPath: '/api/public/payments/checkout'
      preLoaderRoute: typeof ApiPublicPaymentsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/expire': {
      id: '/api/public/cron/expire'
      path: '/api/public/cron/expire'
      fullPath: '/api/public/cron/expire'
      preLoaderRoute: typeof ApiPublicCronExpireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  MovieIdRoute: MovieIdRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
  ApiPublicTranscodeRoute: ApiPublicTranscodeRoute,
  ApiPublicTranscodeKeyRoute: ApiPublicTranscodeKeyRoute,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
  ApiPublicCronExpireRoute: ApiPublicCronExpireRoute,
  ApiPublicPaymentsCheckoutRoute: ApiPublicPaymentsCheckoutRoute,
  ApiPublicPaymentsGiftRoute: ApiPublicPaymentsGiftRoute,
  ApiPublicPaymentsStripeRoute: ApiPublicPaymentsStripeRoute,
  ApiPublicPaymentsStripeVerifyRoute: ApiPublicPaymentsStripeVerifyRoute,
  ApiPublicSmsSendRoute: ApiPublicSmsSendRoute,
  ApiPublicTelegramCheckEnvRoute: ApiPublicTelegramCheckEnvRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
